version: "3"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - .:/usr/tmp/mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=piedao
      - MONGO_INITDB_ROOT_PASSWORD=piedao
      - MONGO_INITDB_DATABASE=piedao

  mongo-seed:
    build:
      context: "."
    volumes:
      - .:/usr/tmp/mongo
    links:
      - mongo
    depends_on:
      - mongo
